// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRbFUaAb7VckJchhjzebscjS7pNTHT7U',
    appId: '1:434235003699:web:a8ba1c6bb78e92cbaa6446',
    messagingSenderId: '434235003699',
    projectId: 'greenfestival-5320b',
    authDomain: 'greenfestival-5320b.firebaseapp.com',
    storageBucket: 'greenfestival-5320b.firebasestorage.app',
    measurementId: 'G-L947KSB08L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP88ik7zsBq3LHyISEn_akif2qiOukyYg',
    appId: '1:434235003699:android:1c93fbbe4ee4fec9aa6446',
    messagingSenderId: '434235003699',
    projectId: 'greenfestival-5320b',
    storageBucket: 'greenfestival-5320b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCs3bF1l6GyXBpwSoA4uXXJ_jjiCB83Es',
    appId: '1:434235003699:ios:df50ae42a902bcebaa6446',
    messagingSenderId: '434235003699',
    projectId: 'greenfestival-5320b',
    storageBucket: 'greenfestival-5320b.firebasestorage.app',
    iosBundleId: 'com.example.chungFestivalKiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCs3bF1l6GyXBpwSoA4uXXJ_jjiCB83Es',
    appId: '1:434235003699:ios:df50ae42a902bcebaa6446',
    messagingSenderId: '434235003699',
    projectId: 'greenfestival-5320b',
    storageBucket: 'greenfestival-5320b.firebasestorage.app',
    iosBundleId: 'com.example.chungFestivalKiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdRbFUaAb7VckJchhjzebscjS7pNTHT7U',
    appId: '1:434235003699:web:3d68387c68b7e576aa6446',
    messagingSenderId: '434235003699',
    projectId: 'greenfestival-5320b',
    authDomain: 'greenfestival-5320b.firebaseapp.com',
    storageBucket: 'greenfestival-5320b.firebasestorage.app',
    measurementId: 'G-H46RNJ6P6K',
  );
}
